project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph:
    image: langfree.png
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
  favicon: favicon.png

metadata-files: [nbdev.yml, sidebar.yml]